name: Staging Deploy

on:
  push:
    branches: [staging]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Staging Deploy Info
        run: echo "Netlify auto deploys from staging branch!"
